
-- 01_schema.sql
-- =========================================================================================
-- STEP 1: Core Database Schema
-- =========================================================================================

-- Main table for stock ratings and prices
CREATE TABLE IF NOT EXISTS public.stock_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    market TEXT,
    name TEXT,
    current_price NUMERIC,
    open NUMERIC,
    premarket_close NUMERIC,
    premarket_open NUMERIC,
    postmarket_close NUMERIC,
    postmarket_open NUMERIC,
    technical_score NUMERIC,
    technical_rating TEXT,
    fetched_date DATE DEFAULT CURRENT_DATE,
    fetched_time TIME DEFAULT CURRENT_TIME,
    session_type TEXT DEFAULT 'post_market',
    rating_change_date DATE,
    previous_price NUMERIC DEFAULT 0,
    price_change NUMERIC DEFAULT 0,
    change_percent NUMERIC DEFAULT 0
);

-- Table for tracking trading performance/returns
CREATE TABLE IF NOT EXISTS public.signal_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    entry_date DATE NOT NULL,
    entry_price NUMERIC NOT NULL,
    entry_rating TEXT NOT NULL,
    exit_date DATE,
    exit_price NUMERIC,
    return_1d NUMERIC,
    return_5d NUMERIC,
    return_20d NUMERIC,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
