-- =========================================================================================
-- MASTER SETUP SCRIPT: Stock Screener Database (V3 ULTRA PERFORMANCE)
-- Combined Version: Tables + Triggers + instant UI Functions + High Performance Architecture
-- UPDATED: Includes "Neutral Skip" Logic and Filtered History Views
-- =========================================================================================

-- 1. Core Database Schema
-- =========================================================================================

-- Main history table
CREATE TABLE IF NOT EXISTS public.stock_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    market TEXT,
    name TEXT,
    current_price NUMERIC,
    open NUMERIC,
    premarket_close NUMERIC,
    premarket_open NUMERIC,
    postmarket_close NUMERIC,
    postmarket_open NUMERIC,
    sector TEXT,
    industry TEXT,
    technical_score NUMERIC,
    technical_rating TEXT,
    fetched_date DATE DEFAULT CURRENT_DATE,
    fetched_time TIME DEFAULT CURRENT_TIME,
    session_type TEXT DEFAULT 'post_market',
    rating_change_date DATE,
    previous_price NUMERIC DEFAULT 0,
    price_change NUMERIC DEFAULT 0,
    change_percent NUMERIC DEFAULT 0,
    -- Performance columns
    daily_change_percent NUMERIC,
    daily_change_amount NUMERIC,
    prev_close_price NUMERIC,
    previous_rating TEXT,
    previous_rating TEXT,
    previous_rating_date DATE,
    accuracy_percent NUMERIC
);

-- Ensure all columns exist for existing databases
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS sector TEXT;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS daily_change_percent NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS daily_change_amount NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS prev_close_price NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS previous_rating TEXT;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS previous_rating_date DATE;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS fetched_time TIME DEFAULT CURRENT_TIME;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS session_type TEXT DEFAULT 'post_market';
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS open NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS premarket_close NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS premarket_open NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS postmarket_close NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS postmarket_open NUMERIC;
ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS accuracy_percent NUMERIC;

-- ADD MISSING CONSTRAINT FOR UPSERT ON stock_ratings
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_stock_rating') THEN
        ALTER TABLE public.stock_ratings ADD CONSTRAINT unique_stock_rating UNIQUE (symbol, fetched_date, fetched_time, session_type);
    END IF;
END $$;

-- Enhance signal_returns for detailed tracking
ALTER TABLE public.signal_returns ADD COLUMN IF NOT EXISTS entry_price NUMERIC;
ALTER TABLE public.signal_returns ADD COLUMN IF NOT EXISTS exit_price NUMERIC;
ALTER TABLE public.signal_returns ADD COLUMN IF NOT EXISTS rating TEXT;
ALTER TABLE public.signal_returns ADD COLUMN IF NOT EXISTS prev_rating TEXT;
ALTER TABLE public.signal_returns ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

-- Add usage constraint for UPSERT
-- Add usage constraint for UPSERT
DO $$
BEGIN
    -- 1. CLEANUP DUPLICATES: Keep only the latest record per symbol/date
    DELETE FROM public.signal_returns
    WHERE id IN (
        SELECT id
        FROM (
            SELECT id,
                   ROW_NUMBER() OVER (PARTITION BY symbol, signal_date ORDER BY created_at DESC, id DESC) as rnum
            FROM public.signal_returns
        ) t
        WHERE t.rnum > 1
    );

    -- 2. ADD CONSTRAINT
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_signal') THEN
        ALTER TABLE public.signal_returns ADD CONSTRAINT unique_signal UNIQUE (symbol, signal_date);
    END IF;
END $$;

-- ULTRA PERFORMANCE TABLE (Stores only the LATEST record per stock for instant UI)
CREATE TABLE IF NOT EXISTS public.latest_stock_ratings (
    symbol TEXT PRIMARY KEY,
    id BIGINT,
    market TEXT,
    name TEXT,
    current_price NUMERIC,
    open NUMERIC,
    premarket_close NUMERIC,
    premarket_open NUMERIC,
    postmarket_close NUMERIC,
    postmarket_open NUMERIC,
    sector TEXT,
    industry TEXT,
    technical_score NUMERIC,
    technical_rating TEXT,
    fetched_date DATE,
    fetched_time TIME,
    session_type TEXT,
    rating_change_date DATE,
    prev_close_price NUMERIC,
    daily_change_percent NUMERIC,
    daily_change_amount NUMERIC,
    previous_rating TEXT,
    previous_rating TEXT,
    previous_rating_date DATE,
    accuracy_percent NUMERIC,
    total_signals INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure previous rating columns exist on latest table
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS previous_rating TEXT;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS previous_rating_date DATE;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS fetched_time TIME;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS session_type TEXT;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS open NUMERIC;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS premarket_close NUMERIC;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS premarket_open NUMERIC;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS postmarket_close NUMERIC;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS postmarket_open NUMERIC;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS accuracy_percent NUMERIC;
ALTER TABLE public.latest_stock_ratings ADD COLUMN IF NOT EXISTS total_signals INTEGER DEFAULT 0;

-- Table for tracking trading performance/returns
CREATE TABLE IF NOT EXISTS public.signal_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    market TEXT,
    signal_date DATE NOT NULL,
    from_rating TEXT NOT NULL,
    to_rating TEXT NOT NULL,
    signal_entry_price NUMERIC NOT NULL,
    price_after_1d NUMERIC,
    price_after_10d NUMERIC,
    price_after_30d NUMERIC,
    return_1d NUMERIC,
    return_10d NUMERIC,
    return_30d NUMERIC,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Performance Optimization Indexes
-- =========================================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Latest Table Indexes (Critical for instant UI loading)
CREATE INDEX IF NOT EXISTS idx_latest_market_rating ON public.latest_stock_ratings (market, technical_rating);
CREATE INDEX IF NOT EXISTS idx_latest_sector ON public.latest_stock_ratings (sector);
CREATE INDEX IF NOT EXISTS idx_latest_daily_change ON public.latest_stock_ratings (daily_change_percent DESC);
CREATE INDEX IF NOT EXISTS idx_latest_rating_date ON public.latest_stock_ratings (rating_change_date DESC);
CREATE INDEX IF NOT EXISTS idx_latest_symbol_trgm ON public.latest_stock_ratings USING gin (symbol gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_latest_name_trgm ON public.latest_stock_ratings USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_latest_accuracy ON public.latest_stock_ratings (accuracy_percent DESC NULLS LAST);

-- History Table Indexes (For deep search & analytics)
CREATE INDEX IF NOT EXISTS idx_stock_ratings_symbol_date ON public.stock_ratings (symbol, fetched_date DESC, fetched_time DESC);
CREATE INDEX IF NOT EXISTS idx_stock_ratings_fetched_date ON public.stock_ratings (fetched_date DESC);

-- 3. Trigger Functions (Automated Calculations on Write)
-- =========================================================================================

-- Trigger A: Sync to 'latest_stock_ratings' (Achieves INSTANT Loading)
-- UPDATED: Includes "Neutral Skip" Logic (Latch latest valid rating)
CREATE OR REPLACE FUNCTION public.sync_latest_stock_rating()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.technical_rating = 'Neutral' THEN
        -- "Keep it the same buy -> sell" logic.
        -- If new is Neutral, only update Price/Date info, but RETAIN the old Rating info.
        UPDATE public.latest_stock_ratings SET
            current_price = NEW.current_price,
            open = NEW.open,
            premarket_close = NEW.premarket_close,
            premarket_open = NEW.premarket_open,
            postmarket_close = NEW.postmarket_close,
            postmarket_open = NEW.postmarket_open,
            technical_score = NEW.technical_score,
            -- DO NOT update technical_rating
            fetched_date = NEW.fetched_date,
            fetched_time = NEW.fetched_time,
            session_type = NEW.session_type,
            -- DO NOT update rating_change_date, previous_rating, etc.
            prev_close_price = NEW.prev_close_price,
            daily_change_percent = NEW.daily_change_percent,
            daily_change_amount = NEW.daily_change_amount,
            accuracy_percent = COALESCE(NEW.accuracy_percent, (SELECT accuracy_percent FROM public.latest_stock_ratings WHERE symbol = NEW.symbol)), -- Preserve old accuracy
            updated_at = NOW()
        WHERE symbol = NEW.symbol;
        
        -- If it doesn't exist yet (First record is Neutral), we insert it as Neutral
        IF NOT FOUND THEN
             INSERT INTO public.latest_stock_ratings (
                symbol, id, market, name, current_price, open, 
                premarket_close, premarket_open, postmarket_close, postmarket_open,
                sector, industry, technical_score, technical_rating,
                fetched_date, fetched_time, session_type, rating_change_date,
                prev_close_price, daily_change_percent, daily_change_amount,
                previous_rating, previous_rating_date, accuracy_percent,
                updated_at
            )
            VALUES (
                NEW.symbol, NEW.id, NEW.market, NEW.name, NEW.current_price, NEW.open,
                NEW.premarket_close, NEW.premarket_open, NEW.postmarket_close, NEW.postmarket_open,
                NEW.sector, NEW.industry, NEW.technical_score, NEW.technical_rating,
                NEW.fetched_date, NEW.fetched_time, NEW.session_type, NEW.rating_change_date,
                NEW.prev_close_price, NEW.daily_change_percent, NEW.daily_change_amount,
                NEW.previous_rating, NEW.previous_rating_date, NEW.accuracy_percent,
                NOW()
            );
        END IF;

    ELSE
        -- Normal Update (Non-Neutral) - Overwrite everything including Rating
        INSERT INTO public.latest_stock_ratings (
            symbol, id, market, name, current_price, open, 
            premarket_close, premarket_open, postmarket_close, postmarket_open,
            sector, industry, technical_score, technical_rating,
            fetched_date, fetched_time, session_type, rating_change_date,
            prev_close_price, daily_change_percent, daily_change_amount,
            previous_rating, previous_rating_date, accuracy_percent,
            updated_at
        )
        VALUES (
            NEW.symbol, NEW.id, NEW.market, NEW.name, NEW.current_price, NEW.open,
            NEW.premarket_close, NEW.premarket_open, NEW.postmarket_close, NEW.postmarket_open,
            NEW.sector, NEW.industry, NEW.technical_score, NEW.technical_rating,
            NEW.fetched_date, NEW.fetched_time, NEW.session_type, NEW.rating_change_date,
            NEW.prev_close_price, NEW.daily_change_percent, NEW.daily_change_amount,
            NEW.previous_rating, NEW.previous_rating_date, NEW.accuracy_percent,
            NOW()
        )
        ON CONFLICT (symbol) DO UPDATE SET
            id = EXCLUDED.id,
            current_price = EXCLUDED.current_price,
            technical_score = EXCLUDED.technical_score,
            technical_rating = EXCLUDED.technical_rating, -- Update Rating
            fetched_date = EXCLUDED.fetched_date,
            fetched_time = EXCLUDED.fetched_time,
            rating_change_date = EXCLUDED.rating_change_date, -- Update Dates
            daily_change_percent = EXCLUDED.daily_change_percent,
            daily_change_amount = EXCLUDED.daily_change_amount,
            previous_rating = EXCLUDED.previous_rating, -- Update Prev
            previous_rating_date = EXCLUDED.previous_rating_date,
            -- Preserve old accuracy if new data doesn't have it yet
            accuracy_percent = COALESCE(EXCLUDED.accuracy_percent, latest_stock_ratings.accuracy_percent),
            total_signals = COALESCE(EXCLUDED.total_signals, latest_stock_ratings.total_signals),
            updated_at = NOW()
        WHERE (EXCLUDED.fetched_date > latest_stock_ratings.fetched_date) 
           OR (EXCLUDED.fetched_date = latest_stock_ratings.fetched_date AND EXCLUDED.fetched_time >= latest_stock_ratings.fetched_time);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_sync_latest_stock_rating ON public.stock_ratings;
CREATE TRIGGER trigger_sync_latest_stock_rating
    AFTER INSERT OR UPDATE ON public.stock_ratings  -- Fire on upsert too
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_latest_stock_rating();

-- Trigger B: Auto Calculate Metrics (Change %, Amount)
CREATE OR REPLACE FUNCTION public.calculate_daily_metrics()
RETURNS TRIGGER AS $$
DECLARE
    prev_record RECORD;
BEGIN
    IF NEW.daily_change_percent IS NULL OR NEW.prev_close_price IS NULL THEN
        SELECT current_price INTO prev_record
        FROM public.stock_ratings
        WHERE symbol = NEW.symbol
        AND (fetched_date < NEW.fetched_date OR (fetched_date = NEW.fetched_date AND fetched_time < NEW.fetched_time))
        ORDER BY fetched_date DESC, fetched_time DESC
        LIMIT 1;

        IF FOUND THEN
            NEW.prev_close_price := prev_record.current_price;
            IF NEW.daily_change_percent IS NULL AND NEW.prev_close_price > 0 THEN
                NEW.daily_change_percent := ((NEW.current_price - NEW.prev_close_price) / NEW.prev_close_price * 100);
                NEW.daily_change_amount := (NEW.current_price - NEW.prev_close_price);
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_calculate_daily_metrics ON public.stock_ratings;
CREATE TRIGGER trigger_calculate_daily_metrics
    BEFORE INSERT OR UPDATE ON public.stock_ratings  -- Fire on upsert too
    FOR EACH ROW
    EXECUTE FUNCTION public.calculate_daily_metrics();

-- Trigger C: Auto Calculate Rating Change Date
-- UPDATED: Include Neutral Skip Logic (Look back to last non-neutral)
CREATE OR REPLACE FUNCTION public.auto_calculate_rating_date()
RETURNS TRIGGER AS $$
DECLARE
    last_record RECORD;
BEGIN
    IF NEW.technical_rating = 'Neutral' THEN
        -- If this new record IS Neutral, we don't strictly care about its "previous" 
        -- logic for signals, but we should populate it for completeness.
        -- It references the last non-neutral rating.
        SELECT technical_rating, rating_change_date, previous_rating, previous_rating_date
        INTO last_record
        FROM public.stock_ratings
        WHERE symbol = NEW.symbol
          AND technical_rating != 'Neutral' -- Ignore other Neutrals
        ORDER BY fetched_date DESC, fetched_time DESC
        LIMIT 1;

        IF NOT FOUND THEN
            NEW.rating_change_date := NEW.fetched_date;
            NEW.previous_rating := NULL;
            NEW.previous_rating_date := NULL;
        ELSE
             -- It's Neutral, so effective rating "change" doesn't strictly tick for signal logic,
             -- but for the record itself:
             NEW.rating_change_date := last_record.rating_change_date;
             NEW.previous_rating := last_record.technical_rating;
             NEW.previous_rating_date := last_record.rating_change_date;
        END IF;

    ELSE
        -- If this new record is NOT Neutral (Buy/Sell), find the last NON-NEUTRAL record
        SELECT technical_rating, rating_change_date, previous_rating, previous_rating_date
        INTO last_record
        FROM public.stock_ratings
        WHERE symbol = NEW.symbol
          AND technical_rating != 'Neutral'
        ORDER BY fetched_date DESC, fetched_time DESC
        LIMIT 1;

        IF NOT FOUND THEN
            -- First non-neutral signal
            NEW.rating_change_date := NEW.fetched_date;
            NEW.previous_rating := NULL;
            NEW.previous_rating_date := NULL;
        ELSIF last_record.technical_rating != NEW.technical_rating THEN
            -- Rating CHANGED (e.g. Sell -> ... -> Buy)
            NEW.rating_change_date := NEW.fetched_date;
            NEW.previous_rating := last_record.technical_rating;
            NEW.previous_rating_date := last_record.rating_change_date;
        ELSE
            -- Rating stayed the SAME (e.g. Buy -> ... -> Buy)
            NEW.rating_change_date := last_record.rating_change_date;
            NEW.previous_rating := last_record.previous_rating;
            NEW.previous_rating_date := last_record.previous_rating_date;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_calc_rating_date ON public.stock_ratings;
CREATE TRIGGER trigger_calc_rating_date
BEFORE INSERT ON public.stock_ratings
FOR EACH ROW
EXECUTE FUNCTION public.auto_calculate_rating_date();

-- 4. ULTRA-FAST UI FUNCTIONS
-- =========================================================================================

-- DASHBOARD STATS
CREATE OR REPLACE FUNCTION public.get_dashboard_stats(p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL) 
RETURNS JSON LANGUAGE plpgsql AS $$
DECLARE 
    result JSON;
    v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
BEGIN
    IF p_date IS NULL OR p_date >= (CURRENT_DATE - INTERVAL '1 day') THEN
        WITH Filtered AS (
            SELECT technical_rating, fetched_date
            FROM public.latest_stock_ratings l
            WHERE (p_market IS NULL OR p_market = '' OR l.market = p_market)
            AND l.symbol NOT LIKE 'OTC:%'
            AND l.current_price >= 0.2 
        )
        SELECT json_build_object(
            'total_positive', COUNT(*) FILTER (WHERE technical_rating IN ('Strong Buy', 'Buy')),
            'total_negative', COUNT(*) FILTER (WHERE technical_rating IN ('Strong Sell', 'Sell')),
            'strong_buy', COUNT(*) FILTER (WHERE technical_rating = 'Strong Buy'),
            'buy', COUNT(*) FILTER (WHERE technical_rating = 'Buy'),
            'strong_sell', COUNT(*) FILTER (WHERE technical_rating = 'Strong Sell'),
            'sell', COUNT(*) FILTER (WHERE technical_rating = 'Sell'),
            'neutral', COUNT(*) FILTER (WHERE technical_rating = 'Neutral'),
            'date', MAX(fetched_date) 
        ) INTO result
        FROM Filtered;
    ELSE
        WITH LatestPerSymbol AS (
            SELECT DISTINCT ON (sr.symbol) technical_rating, fetched_date, current_price, market
            FROM public.stock_ratings sr
            WHERE sr.fetched_date >= (v_base_date - INTERVAL '60 days') AND sr.fetched_date <= v_base_date
            ORDER BY sr.symbol, sr.fetched_date DESC, sr.fetched_time DESC
        )
        SELECT json_build_object(
            'total_positive', COUNT(*) FILTER (WHERE technical_rating IN ('Strong Buy', 'Buy')),
            'total_negative', COUNT(*) FILTER (WHERE technical_rating IN ('Strong Sell', 'Sell')),
            'strong_buy', COUNT(*) FILTER (WHERE technical_rating = 'Strong Buy'),
            'buy', COUNT(*) FILTER (WHERE technical_rating = 'Buy'),
            'strong_sell', COUNT(*) FILTER (WHERE technical_rating = 'Strong Sell'),
            'sell', COUNT(*) FILTER (WHERE technical_rating = 'Sell'),
            'neutral', COUNT(*) FILTER (WHERE technical_rating = 'Neutral'),
            'date', MAX(fetched_date) 
        ) INTO result
        FROM LatestPerSymbol l
        WHERE (p_market IS NULL OR p_market = '' OR l.market = p_market)
        AND l.current_price >= 0.2;
    END IF;
    RETURN result;
END; $$;

-- TOP GAINERS
CREATE OR REPLACE FUNCTION public.get_top_gainers(
    p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL, p_limit INTEGER DEFAULT 3
)
RETURNS TABLE (
    res_symbol TEXT, res_market TEXT, res_name TEXT, res_price NUMERIC, res_change_pct NUMERIC, res_date DATE
) LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
    SELECT symbol, market, name, current_price, COALESCE(daily_change_percent, 0), fetched_date
    FROM public.latest_stock_ratings l
    WHERE (p_market IS NULL OR p_market = '' OR l.market = p_market)
      AND l.symbol NOT LIKE 'OTC:%' AND l.current_price >= 0.2
      AND l.technical_rating != 'Neutral'
      AND l.daily_change_percent IS NOT NULL AND l.daily_change_percent > 0
    ORDER BY daily_change_percent DESC LIMIT p_limit;
END; $$;

 
-- TOP ACCURACY STOCKS (All Time)
DROP FUNCTION IF EXISTS public.get_top_accuracy_stocks(TEXT, INTEGER) CASCADE;
DROP FUNCTION IF EXISTS public.get_top_accuracy_stocks CASCADE;

CREATE OR REPLACE FUNCTION public.get_top_accuracy_stocks(
    p_market TEXT DEFAULT NULL, 
    p_limit INTEGER DEFAULT 3
)
RETURNS TABLE (
    res_symbol TEXT, 
    res_market TEXT, 
    res_name TEXT, 
    res_price NUMERIC, 
    res_change_pct NUMERIC, 
    res_accuracy NUMERIC,
    res_total_signals INTEGER
) LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
    SELECT symbol, market, name, current_price, COALESCE(daily_change_percent, 0), accuracy_percent, total_signals
    FROM public.latest_stock_ratings l
    WHERE (p_market IS NULL OR p_market = '' OR l.market = p_market)
      AND l.symbol NOT LIKE 'OTC:%' 
      AND l.current_price >= 0.2
      AND l.accuracy_percent IS NOT NULL 
      AND l.accuracy_percent > 0
    ORDER BY accuracy_percent DESC, total_signals DESC, daily_change_percent DESC
    LIMIT p_limit;
END; $$;

-- GET UNIQUE SECTORS (For Sector Filter Dropdown)
CREATE OR REPLACE FUNCTION public.get_sectors()
RETURNS TABLE (sector TEXT) LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT l.sector
    FROM public.latest_stock_ratings l
    WHERE l.sector IS NOT NULL AND l.sector != ''
    ORDER BY l.sector ASC;
END; $$;

-- CALCULATE ALL ACCURACIES (Bulk Update)
CREATE OR REPLACE FUNCTION public.calculate_all_accuracies()
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    WITH SignalStats AS (
        SELECT 
            symbol,
            COUNT(*) as total_signals,
            COUNT(*) FILTER (WHERE return_1d > 0.2) as wins
        FROM public.signal_returns
        WHERE return_1d IS NOT NULL
        GROUP BY symbol
    )
    UPDATE public.latest_stock_ratings l
    SET 
        accuracy_percent = (s.wins::numeric / s.total_signals::numeric) * 100,
        total_signals = s.total_signals
    FROM SignalStats s
    WHERE l.symbol = s.symbol AND s.total_signals > 0;
END; $$;

-- MAIN STOCK LIST (Updated with Neutral Filter)
-- Drop first to allow return type change
DROP FUNCTION IF EXISTS public.get_stocks(TEXT, DATE, TEXT, TEXT, TEXT, TEXT, TEXT, INTEGER, INTEGER, INTEGER, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.get_stocks CASCADE;

CREATE OR REPLACE FUNCTION public.get_stocks(
    p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL, p_search TEXT DEFAULT NULL,
    p_rating TEXT DEFAULT NULL, p_tech_rating TEXT DEFAULT NULL,
    p_sort_by TEXT DEFAULT 'rating_change_date', p_sort_order TEXT DEFAULT 'desc',
    p_limit INTEGER DEFAULT 50, p_offset INTEGER DEFAULT 0, p_lookback INTEGER DEFAULT 60,
    p_sector TEXT DEFAULT NULL
)
RETURNS TABLE (
    res_id BIGINT, res_symbol TEXT, res_market TEXT, res_name TEXT, res_current_price NUMERIC,
    res_open NUMERIC, res_premarket_close NUMERIC, res_premarket_open NUMERIC, res_postmarket_close NUMERIC, res_postmarket_open NUMERIC,
    res_sector TEXT, res_industry TEXT, res_previous_price NUMERIC, res_change NUMERIC, res_change_pct NUMERIC,
    res_technical_score NUMERIC, res_technical_rating TEXT, res_previous_rating TEXT, res_rating_change_date DATE,
    res_fetched_date DATE, res_fetched_time TIME,
    res_accuracy_percent NUMERIC,
    res_total_signals INTEGER -- [NEW]
) AS $$
DECLARE 
    v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
BEGIN
    IF p_date IS NULL OR p_date >= (CURRENT_DATE - INTERVAL '1 day') THEN
        RETURN QUERY
        WITH CandidateIds AS (
            SELECT l.*,
                   SPLIT_PART(l.symbol, ':', 1) as exchange,
                   COALESCE(NULLIF(SPLIT_PART(l.symbol, ':', 2), ''), l.symbol) as symbol_only
            FROM public.latest_stock_ratings l
            WHERE l.current_price >= 0.2 
              AND l.symbol NOT LIKE 'OTC:%'
              AND (p_market IS NULL OR p_market = '' OR l.market = p_market)
              AND (p_sector IS NULL OR p_sector = '' OR p_sector = 'All' OR l.sector = p_sector)
              AND (p_rating IS NULL OR p_rating = '' OR l.technical_rating = p_rating)
              AND (p_tech_rating IS NULL OR p_tech_rating = ''
                   OR (p_tech_rating = 'Positive' AND l.technical_rating IN ('Strong Buy', 'Buy'))
                   OR (p_tech_rating = 'Negative' AND l.technical_rating IN ('Strong Sell', 'Sell')))
              AND (p_search IS NULL OR p_search = '' OR l.symbol ILIKE '%' || p_search || '%' OR l.name ILIKE '%' || p_search || '%')
        ), SortedIds AS (
            SELECT * FROM CandidateIds
            ORDER BY
                -- Manual Sorting mapping from Frontend TanStack Table IDs
                CASE WHEN (p_sort_by = 'symbol' OR p_sort_by = 'Symbol') AND p_sort_order = 'asc' THEN symbol_only END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'symbol' OR p_sort_by = 'Symbol') AND p_sort_order = 'desc' THEN symbol_only END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'exchange' OR p_sort_by = 'exchange') AND p_sort_order = 'asc' THEN exchange END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'exchange' OR p_sort_by = 'exchange') AND p_sort_order = 'desc' THEN exchange END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'asc' THEN current_price END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'desc' THEN current_price END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'sector' AND p_sort_order = 'asc' THEN sector END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'sector' AND p_sort_order = 'desc' THEN sector END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'change' AND p_sort_order = 'asc' THEN daily_change_amount END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'change' AND p_sort_order = 'desc' THEN daily_change_amount END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'changePercent' OR p_sort_by = 'daily_change_percent') AND p_sort_order = 'asc' THEN daily_change_percent END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'changePercent' OR p_sort_by = 'daily_change_percent') AND p_sort_order = 'desc' THEN daily_change_percent END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'Technical_Rating' OR p_sort_by = 'technical_rating') AND p_sort_order = 'asc' THEN technical_rating END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'Technical_Rating' OR p_sort_by = 'technical_rating') AND p_sort_order = 'desc' THEN technical_rating END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'rating_change_date' OR p_sort_by = 'fetched_date') AND p_sort_order = 'asc' THEN rating_change_date END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'rating_change_date' OR p_sort_by = 'fetched_date') AND p_sort_order = 'desc' THEN rating_change_date END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'asc' THEN accuracy_percent END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'desc' THEN accuracy_percent END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'asc' THEN total_signals END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'desc' THEN total_signals END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'asc' THEN daily_change_percent END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'desc' THEN daily_change_percent END DESC NULLS LAST,
                symbol_only ASC
            LIMIT p_limit OFFSET p_offset
        )
        SELECT 
            id, symbol, market, name, current_price, 
            open, premarket_close, premarket_open, postmarket_close, postmarket_open,
            sector, industry,
            prev_close_price, daily_change_amount, daily_change_percent,
            technical_score, technical_rating, 
            previous_rating, rating_change_date, fetched_date, fetched_time,
            accuracy_percent, total_signals
        FROM SortedIds;
    ELSE
        RETURN QUERY
        WITH LatestPerSymbol AS (
            SELECT DISTINCT ON (sr.symbol) sr.*,
                   SPLIT_PART(sr.symbol, ':', 1) as exchange,
                   COALESCE(NULLIF(SPLIT_PART(sr.symbol, ':', 2), ''), sr.symbol) as symbol_only
            FROM public.stock_ratings sr
            WHERE sr.fetched_date >= (v_base_date - INTERVAL '60 days') AND sr.fetched_date <= v_base_date
              AND sr.current_price >= 0.2 
              AND sr.symbol NOT LIKE 'OTC:%'
              AND (p_market IS NULL OR p_market = '' OR sr.market = p_market)
              AND (p_sector IS NULL OR p_sector = '' OR p_sector = 'All' OR sr.sector = p_sector)
              AND (p_rating IS NULL OR p_rating = '' OR sr.technical_rating = p_rating)
              AND (p_tech_rating IS NULL OR p_tech_rating = ''
                   OR (p_tech_rating = 'Positive' AND sr.technical_rating IN ('Strong Buy', 'Buy'))
                   OR (p_tech_rating = 'Negative' AND sr.technical_rating IN ('Strong Sell', 'Sell')))
              AND (p_search IS NULL OR p_search = '' OR sr.symbol ILIKE '%' || p_search || '%' OR sr.name ILIKE '%' || p_search || '%')
            ORDER BY sr.symbol, sr.fetched_date DESC, sr.fetched_time DESC
        ), SortedHistory AS (
            SELECT * FROM LatestPerSymbol
            ORDER BY
                -- Manual Sorting mapping from Frontend TanStack Table IDs
                CASE WHEN (p_sort_by = 'symbol' OR p_sort_by = 'Symbol') AND p_sort_order = 'asc' THEN symbol_only END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'symbol' OR p_sort_by = 'Symbol') AND p_sort_order = 'desc' THEN symbol_only END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'exchange' OR p_sort_by = 'exchange') AND p_sort_order = 'asc' THEN exchange END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'exchange' OR p_sort_by = 'exchange') AND p_sort_order = 'desc' THEN exchange END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'asc' THEN current_price END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'desc' THEN current_price END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'sector' AND p_sort_order = 'asc' THEN sector END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'sector' AND p_sort_order = 'desc' THEN sector END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'change' AND p_sort_order = 'asc' THEN daily_change_amount END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'change' AND p_sort_order = 'desc' THEN daily_change_amount END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'changePercent' OR p_sort_by = 'daily_change_percent') AND p_sort_order = 'asc' THEN daily_change_percent END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'changePercent' OR p_sort_by = 'daily_change_percent') AND p_sort_order = 'desc' THEN daily_change_percent END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'Technical_Rating' OR p_sort_by = 'technical_rating') AND p_sort_order = 'asc' THEN technical_rating END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'Technical_Rating' OR p_sort_by = 'technical_rating') AND p_sort_order = 'desc' THEN technical_rating END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'rating_change_date' OR p_sort_by = 'fetched_date') AND p_sort_order = 'asc' THEN rating_change_date END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'rating_change_date' OR p_sort_by = 'fetched_date') AND p_sort_order = 'desc' THEN rating_change_date END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'asc' THEN accuracy_percent END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'desc' THEN accuracy_percent END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'asc' THEN total_signals END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'desc' THEN total_signals END DESC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'asc' THEN daily_change_percent END ASC NULLS LAST,
                CASE WHEN (p_sort_by = 'accuracy' OR p_sort_by = 'accuracy_percent') AND p_sort_order = 'desc' THEN daily_change_percent END DESC NULLS LAST,
                symbol_only ASC
            LIMIT p_limit OFFSET p_offset
        )
        SELECT id, symbol, market, name, current_price, open, premarket_close, premarket_open, postmarket_close, postmarket_open,
               sector, industry, prev_close_price, daily_change_amount, daily_change_percent,
               technical_score, technical_rating, previous_rating, rating_change_date, fetched_date, fetched_time,
               accuracy_percent, total_signals
        FROM SortedHistory;
    END IF;
END; $$ LANGUAGE plpgsql;

-- TOTAL COUNT (Updated with Neutral Filter)
CREATE OR REPLACE FUNCTION public.get_stocks_count_filtered(
    p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL, p_search TEXT DEFAULT NULL, 
    p_rating TEXT DEFAULT NULL, p_tech_rating TEXT DEFAULT NULL, p_lookback INT DEFAULT 60,
    p_sector TEXT DEFAULT NULL
)
RETURNS TABLE (res_total BIGINT) LANGUAGE plpgsql AS $$
DECLARE 
    v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
BEGIN
    IF p_date IS NULL OR p_date >= (CURRENT_DATE - INTERVAL '1 day') THEN
        RETURN QUERY SELECT COUNT(*) FROM public.latest_stock_ratings l
        WHERE l.current_price >= 0.2 
          AND l.symbol NOT LIKE 'OTC:%'
          AND (p_market IS NULL OR p_market = '' OR l.market = p_market)
          AND (p_sector IS NULL OR p_sector = '' OR p_sector = 'All' OR l.sector = p_sector)
          AND (p_rating IS NULL OR p_rating = '' OR l.technical_rating = p_rating)
          AND (p_tech_rating IS NULL OR p_tech_rating = ''
              OR (p_tech_rating = 'Positive' AND l.technical_rating IN ('Strong Buy', 'Buy'))
              OR (p_tech_rating = 'Negative' AND l.technical_rating IN ('Strong Sell', 'Sell')))
          AND (p_search IS NULL OR p_search = '' OR l.symbol ILIKE '%' || p_search || '%' OR l.name ILIKE '%' || p_search || '%');
    ELSE
        RETURN QUERY WITH Latest AS (
            SELECT DISTINCT ON (sr.symbol) sr.id FROM public.stock_ratings sr
            WHERE sr.fetched_date >= (v_base_date - INTERVAL '60 days') AND sr.fetched_date <= v_base_date
              AND sr.current_price >= 0.2 
              AND sr.symbol NOT LIKE 'OTC:%'
              AND (p_market IS NULL OR p_market = '' OR sr.market = p_market)
              AND (p_sector IS NULL OR p_sector = '' OR p_sector = 'All' OR sr.sector = p_sector)
              AND (p_rating IS NULL OR p_rating = '' OR sr.technical_rating = p_rating)
              AND (p_tech_rating IS NULL OR p_tech_rating = ''
                   OR (p_tech_rating = 'Positive' AND sr.technical_rating IN ('Strong Buy', 'Buy'))
                   OR (p_tech_rating = 'Negative' AND sr.technical_rating IN ('Strong Sell', 'Sell')))
              AND (p_search IS NULL OR p_search = '' OR sr.symbol ILIKE '%' || p_search || '%' OR sr.name ILIKE '%' || p_search || '%')
            ORDER BY sr.symbol, sr.fetched_date DESC, sr.fetched_time DESC
        ) SELECT COUNT(*) FROM Latest;
    END IF;
END; $$;

-- 5. BACKFILL LOGIC (Updated with Neutral Skip)
-- =========================================================================================

-- Function to recalculate rating history for a specific symbol (Neutral Skip Logic)
CREATE OR REPLACE FUNCTION public.recalculate_symbol_history(p_symbol TEXT)
RETURNS VOID AS $$
DECLARE
    r RECORD;
    curr_rating TEXT := NULL;
    curr_change_date DATE := NULL;
    prev_rating TEXT := NULL;
    prev_rating_date DATE := NULL;
BEGIN
    FOR r IN
        SELECT id, fetched_date, technical_rating, fetched_time
        FROM public.stock_ratings
        WHERE symbol = p_symbol
        ORDER BY fetched_date ASC, fetched_time ASC
    LOOP
        -- If Neutral, SKIP logic for signal state (keep valid) but update row pointers
        IF r.technical_rating = 'Neutral' THEN
             UPDATE public.stock_ratings
             SET rating_change_date = curr_change_date,
                 previous_rating = prev_rating,
                 previous_rating_date = prev_rating_date
             WHERE id = r.id;
        ELSE
            -- Non-Neutral (Buy/Sell)
            IF curr_rating IS NULL THEN
                curr_rating := r.technical_rating;
                curr_change_date := r.fetched_date;
                prev_rating := NULL;
                prev_rating_date := NULL;
                
                UPDATE public.stock_ratings
                SET rating_change_date = curr_change_date,
                    previous_rating = NULL,
                    previous_rating_date = NULL
                WHERE id = r.id;
                
            ELSIF r.technical_rating != curr_rating THEN
                -- Change Detected
                prev_rating := curr_rating;
                prev_rating_date := curr_change_date;
                
                curr_rating := r.technical_rating;
                curr_change_date := r.fetched_date;
                
                UPDATE public.stock_ratings
                SET rating_change_date = curr_change_date,
                    previous_rating = prev_rating,
                    previous_rating_date = prev_rating_date
                WHERE id = r.id;
            ELSE
                -- Same Rating
                UPDATE public.stock_ratings
                SET rating_change_date = curr_change_date,
                    previous_rating = prev_rating,
                    previous_rating_date = prev_rating_date
                WHERE id = r.id;
            END IF;
        END IF;
    END LOOP;
    
    PERFORM public.sync_latest_stock_rating_manual(p_symbol);
END;
$$ LANGUAGE plpgsql;

-- Manual Sync with Neutral Skip Logic
-- MUST MATCH TRIGGER LOGIC: Latch to last VALID rating
CREATE OR REPLACE FUNCTION public.sync_latest_stock_rating_manual(p_symbol TEXT)
RETURNS VOID AS $$
DECLARE
    latest_valid_rec RECORD;
    latest_real_rec RECORD;
BEGIN
    SELECT * INTO latest_valid_rec
    FROM public.stock_ratings
    WHERE symbol = p_symbol AND technical_rating != 'Neutral'
    ORDER BY fetched_date DESC, fetched_time DESC
    LIMIT 1;

    SELECT * INTO latest_real_rec
    FROM public.stock_ratings
    WHERE symbol = p_symbol
    ORDER BY fetched_date DESC, fetched_time DESC
    LIMIT 1;
    
    IF FOUND THEN
        IF latest_valid_rec IS NULL THEN
            latest_valid_rec := latest_real_rec;
        END IF;

        INSERT INTO public.latest_stock_ratings (
            symbol, id, market, name, current_price, open, premarket_close, premarket_open, postmarket_close, postmarket_open,
            sector, industry, technical_score, technical_rating, fetched_date, fetched_time, session_type,
            rating_change_date, prev_close_price, daily_change_percent, daily_change_amount, previous_rating, previous_rating_date, accuracy_percent
        ) VALUES (
            latest_real_rec.symbol, latest_real_rec.id, latest_real_rec.market, latest_real_rec.name, 
            latest_real_rec.current_price, latest_real_rec.open, latest_real_rec.premarket_close, latest_real_rec.premarket_open, latest_real_rec.postmarket_close, latest_real_rec.postmarket_open,
            latest_real_rec.sector, latest_real_rec.industry, latest_real_rec.technical_score, 
            latest_valid_rec.technical_rating, 
            latest_real_rec.fetched_date, latest_real_rec.fetched_time, latest_real_rec.session_type,
            latest_valid_rec.rating_change_date, 
            latest_real_rec.prev_close_price, latest_real_rec.daily_change_percent, latest_real_rec.daily_change_amount, 
            latest_valid_rec.previous_rating, latest_valid_rec.previous_rating_date, latest_real_rec.accuracy_percent
        )
        ON CONFLICT (symbol) DO UPDATE SET
            id = EXCLUDED.id,
            current_price = EXCLUDED.current_price,
            technical_rating = EXCLUDED.technical_rating,
            fetched_date = EXCLUDED.fetched_date,
            fetched_time = EXCLUDED.fetched_time,
            rating_change_date = EXCLUDED.rating_change_date,
            daily_change_percent = EXCLUDED.daily_change_percent,
            daily_change_amount = EXCLUDED.daily_change_amount,
            previous_rating = EXCLUDED.previous_rating,
            previous_rating_date = EXCLUDED.previous_rating_date,
            accuracy_percent = EXCLUDED.accuracy_percent,
            updated_at = NOW();
    END IF;
END;
$$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload schema';

-- 6. AUTOMATION TRIGGERS (Future Proofing)
-- =========================================================================================

-- Function to handle NEW signals automatically when stock_ratings is inserted
CREATE OR REPLACE FUNCTION public.manage_new_signal_entry()
RETURNS TRIGGER AS $$
DECLARE
    last_signal RECORD;
    prev_rating TEXT;
BEGIN
    -- Only care if not Neutral
    IF NEW.technical_rating != 'Neutral' THEN
        
        -- Get the most recent signal for this symbol
        SELECT * INTO last_signal 
        FROM public.signal_returns
        WHERE symbol = NEW.symbol
        ORDER BY signal_date DESC
        LIMIT 1;

        -- If no previous signal, or the last signal was "completed" (has exit price),
        -- OR the rating has changed from the last signal's "to_rating"
        IF last_signal IS NULL OR last_signal.exit_price IS NOT NULL OR last_signal.to_rating != NEW.technical_rating THEN
            
            -- Prepare "from_rating"
            IF last_signal IS NOT NULL AND last_signal.exit_price IS NULL AND last_signal.to_rating != NEW.technical_rating THEN
                -- The previous signal is technically "ended" by this new opposite signal (if we treat change as exit)
                -- But our logic is: Exit is NEXT TRADING DAY.
                -- Use standard logic: JUST INSERT NEW SIGNAL. logic for closing old signal is time-based (next day).
                prev_rating := last_signal.to_rating;
            ELSE
                -- Fetch previous rating from stock_ratings history if needed, or default 'Neutral'
                prev_rating := COALESCE(NEW.previous_rating, 'Neutral');
            END IF;

            -- Check if we already have a signal for this DATE (deduplication)
            IF NOT EXISTS (SELECT 1 FROM public.signal_returns WHERE symbol = NEW.symbol AND signal_date = NEW.fetched_date) THEN
                 INSERT INTO public.signal_returns (symbol, signal_date, from_rating, to_rating, signal_entry_price, status)
                 VALUES (
                     NEW.symbol, 
                     NEW.fetched_date, 
                     prev_rating, 
                     NEW.technical_rating, 
                     COALESCE(NEW.open, NEW.current_price),
                     'active'
                 );
            END IF;
        END IF;

        -- CHECK FOR EXIT of Previous Active Signal
        -- If there is an active signal from a PREVIOUS date, this row is the EXIT (Next Trading Day)
        -- (Logic: Iterate pending signals)
        UPDATE public.signal_returns
        SET exit_price = COALESCE(NEW.open, NEW.current_price),
            return_1d = CASE WHEN signal_entry_price > 0 THEN 
                ((COALESCE(NEW.open, NEW.current_price) - signal_entry_price) / signal_entry_price) * 100 
                ELSE 0 END,
            status = 'closed',
            updated_at = NOW()
        WHERE symbol = NEW.symbol
          AND status = 'active'
          AND signal_date < NEW.fetched_date;
          
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_manage_signals ON public.stock_ratings;
CREATE TRIGGER trigger_manage_signals
    AFTER INSERT ON public.stock_ratings
    FOR EACH ROW
    EXECUTE FUNCTION public.manage_new_signal_entry();


-- Function to Auto-Update Accuracy on Signal Close
CREATE OR REPLACE FUNCTION public.auto_update_accuracy()
RETURNS TRIGGER AS $$
DECLARE
    total_sig INT;
    wins INT;
    new_accuracy NUMERIC;
BEGIN
    -- Only update if return_1d is set (signal closed)
    IF NEW.return_1d IS NOT NULL THEN
        SELECT COUNT(*), COUNT(*) FILTER (WHERE return_1d > 0.2)
        INTO total_sig, wins
        FROM public.signal_returns
        WHERE symbol = NEW.symbol
          AND return_1d IS NOT NULL;
          
        IF total_sig > 0 THEN
            new_accuracy := (wins::numeric / total_sig::numeric) * 100;
            
            UPDATE public.latest_stock_ratings
            SET accuracy_percent = new_accuracy,
                total_signals = total_sig,
                updated_at = NOW()
            WHERE symbol = NEW.symbol;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_accuracy ON public.signal_returns;
CREATE TRIGGER trigger_update_accuracy
    AFTER UPDATE OF return_1d ON public.signal_returns
    FOR EACH ROW
    EXECUTE FUNCTION public.auto_update_accuracy();
