-- =========================================================================================
-- MASTER SETUP SCRIPT: Stock Screener Database
-- Combined Version (Tables, Indexes, UI Functions, Screener Logic)
-- =========================================================================================

-- 1. Core Database Schema
-- =========================================================================================

-- Main table for stock ratings and prices
CREATE TABLE IF NOT EXISTS public.stock_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    market TEXT,
    name TEXT,
    current_price NUMERIC,
    technical_score NUMERIC,
    technical_rating TEXT,
    fetched_date DATE DEFAULT CURRENT_DATE,
    fetched_time TIME DEFAULT CURRENT_TIME,
    session_type TEXT DEFAULT 'post_market',
    rating_change_date DATE,
    previous_price NUMERIC DEFAULT 0,
    price_change NUMERIC DEFAULT 0,
    change_percent NUMERIC DEFAULT 0
);

-- Table for tracking trading performance/returns
CREATE TABLE IF NOT EXISTS public.signal_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    entry_date DATE NOT NULL,
    entry_price NUMERIC NOT NULL,
    entry_rating TEXT NOT NULL,
    exit_date DATE,
    exit_price NUMERIC,
    return_1d NUMERIC,
    return_5d NUMERIC,
    return_20d NUMERIC,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Performance Optimization Indexes
-- =========================================================================================

-- Optimize LATERAL Join Performance
CREATE INDEX IF NOT EXISTS idx_stock_ratings_lateral_opt 
ON public.stock_ratings (symbol, fetched_date DESC, fetched_time DESC, technical_rating)
INCLUDE (current_price);

-- Optimize Main Screener Filtering
CREATE INDEX IF NOT EXISTS idx_stock_ratings_screener_cover 
ON public.stock_ratings (fetched_date DESC, market, technical_rating)
INCLUDE (symbol, name, current_price, technical_score, rating_change_date)
WHERE symbol NOT LIKE 'OTC:%';

-- Speed up deduplication sorting (DISTINCT ON symbol)
CREATE INDEX IF NOT EXISTS idx_stock_ratings_symbol_lookup 
ON public.stock_ratings (symbol);

-- Optimize date-based signal change tracking
CREATE INDEX IF NOT EXISTS idx_stock_ratings_signal_date 
ON public.stock_ratings (rating_change_date DESC);

-- Optimize Search Performance (Text Search)
CREATE INDEX IF NOT EXISTS idx_stock_ratings_symbol_trgm 
ON public.stock_ratings (symbol text_pattern_ops);

-- Index for signal_returns lookups
CREATE INDEX IF NOT EXISTS idx_signal_returns_symbol_date 
ON public.signal_returns (symbol, entry_date);

-- 3. UI & Dashboard Functions
-- =========================================================================================

DROP FUNCTION IF EXISTS public.get_dashboard_stats(text,date);
DROP FUNCTION IF EXISTS public.get_stocks_count_filtered(text,date,text,text,text);
DROP FUNCTION IF EXISTS public.get_top_gainers(text,date,integer);

-- DASHBOARD STATS
CREATE OR REPLACE FUNCTION public.get_dashboard_stats(
    target_market TEXT DEFAULT NULL,
    target_date DATE DEFAULT NULL
) 
RETURNS JSON 
LANGUAGE plpgsql AS $$
DECLARE 
    result JSON;
    base_date DATE := COALESCE(target_date, CURRENT_DATE);
BEGIN
    WITH StockCandidates AS (
        SELECT sr.*
        FROM public.stock_ratings sr
        WHERE sr.fetched_date >= (base_date - INTERVAL '90 days')
          AND sr.fetched_date <= base_date
          AND (target_market IS NULL OR target_market = '' OR sr.market = target_market)
          AND sr.symbol NOT LIKE 'OTC:%'
    ),
    UniqueStocks AS (
        SELECT DISTINCT ON (t.symbol) t.*
        FROM StockCandidates t
        ORDER BY t.symbol, t.fetched_date DESC, t.fetched_time DESC
    )
    SELECT json_build_object(
        'total_positive', COUNT(*) FILTER (WHERE u.technical_rating IN ('Strong Buy', 'Buy')),
        'total_negative', COUNT(*) FILTER (WHERE u.technical_rating IN ('Strong Sell', 'Sell')),
        'strong_buy', COUNT(*) FILTER (WHERE u.technical_rating = 'Strong Buy'),
        'buy', COUNT(*) FILTER (WHERE u.technical_rating = 'Buy'),
        'strong_sell', COUNT(*) FILTER (WHERE u.technical_rating = 'Strong Sell'),
        'sell', COUNT(*) FILTER (WHERE u.technical_rating = 'Sell'),
        'neutral', COUNT(*) FILTER (WHERE u.technical_rating = 'Neutral'),
        'date', MAX(u.fetched_date) 
    ) INTO result
    FROM UniqueStocks u
    WHERE u.current_price >= 0.2
      AND u.technical_rating != 'Neutral';
    
    RETURN result;
END; $$;

-- TOTAL COUNT FILTERED
CREATE OR REPLACE FUNCTION public.get_stocks_count_filtered(
    target_market TEXT DEFAULT NULL,
    target_date DATE DEFAULT NULL,
    search_term TEXT DEFAULT NULL,
    target_rating TEXT DEFAULT NULL,
    target_technical_rating TEXT DEFAULT NULL
)
RETURNS TABLE (total BIGINT) 
LANGUAGE plpgsql AS $$
DECLARE
    base_date DATE := COALESCE(target_date, CURRENT_DATE);
    lookback_days INT := CASE WHEN (search_term IS NOT NULL AND search_term != '') THEN 365 ELSE 90 END;
BEGIN
    RETURN QUERY 
    WITH StockCandidates AS (
        SELECT sr.*
        FROM public.stock_ratings sr
        WHERE sr.fetched_date >= (base_date - (lookback_days || ' days')::INTERVAL)
          AND sr.fetched_date <= base_date
          AND (target_market IS NULL OR target_market = '' OR sr.market = target_market)
          AND sr.symbol NOT LIKE 'OTC:%'
    ),
    UniqueStocks AS (
        SELECT DISTINCT ON (t.symbol) 
            t.symbol, t.technical_rating, t.name, t.current_price
        FROM StockCandidates t
        WHERE (search_term IS NULL OR search_term = '' OR t.symbol ILIKE '%' || search_term || '%' OR t.name ILIKE '%' || search_term || '%')
        ORDER BY t.symbol, t.fetched_date DESC, t.fetched_time DESC
    )
    SELECT COUNT(*) 
    FROM UniqueStocks u
    WHERE u.current_price >= 0.2
      AND u.technical_rating != 'Neutral'
      AND (target_rating IS NULL OR target_rating = '' OR u.technical_rating = target_rating)
      AND (target_technical_rating IS NULL OR target_technical_rating = ''
           OR (target_technical_rating = 'Positive' AND u.technical_rating IN ('Strong Buy', 'Buy'))
           OR (target_technical_rating = 'Negative' AND u.technical_rating IN ('Strong Sell', 'Sell')));
END; $$;

-- TOP GAINERS
CREATE OR REPLACE FUNCTION public.get_top_gainers(
    target_market TEXT DEFAULT NULL,
    target_date DATE DEFAULT NULL,
    limit_val INT DEFAULT 3
)
RETURNS TABLE (
    symbol TEXT, market TEXT, name TEXT, change_percent NUMERIC
) 
LANGUAGE plpgsql AS $$
DECLARE
    base_date DATE := COALESCE(target_date, CURRENT_DATE);
BEGIN
    RETURN QUERY
    WITH StockCandidates AS (
        SELECT sr.*
        FROM public.stock_ratings sr
        WHERE sr.fetched_date >= (base_date - INTERVAL '90 days')
          AND sr.fetched_date <= base_date
          AND (target_market IS NULL OR target_market = '' OR sr.market = target_market)
          AND sr.symbol NOT LIKE 'OTC:%'
    ),
    UniqueStocks AS (
        SELECT DISTINCT ON (t.symbol) t.*
        FROM StockCandidates t
        ORDER BY t.symbol, t.fetched_date DESC, t.fetched_time DESC
    ),
    FilteredStocks AS (
        SELECT u.*
        FROM UniqueStocks u
        WHERE u.current_price >= 0.2
          AND u.technical_rating IN ('Strong Buy', 'Buy')
    ),
    WithHistory AS (
        SELECT 
            f.symbol as f_symbol, f.market as f_market, f.name as f_name, f.current_price as f_current_price,
            pre.h_price
        FROM FilteredStocks f
        LEFT JOIN LATERAL (
            SELECT p.current_price as h_price
            FROM public.stock_ratings p
            WHERE p.symbol = f.symbol
              AND (p.fetched_date < f.fetched_date OR (p.fetched_date = f.fetched_date AND p.fetched_time < f.fetched_time))
              AND p.technical_rating != f.technical_rating
              AND p.technical_rating != 'Neutral'
            ORDER BY p.fetched_date DESC, p.fetched_time DESC
            LIMIT 1
        ) pre ON TRUE
    ),
    CalculatedResults AS (
        SELECT 
            w.f_symbol, w.f_market, w.f_name,
            CASE WHEN w.h_price > 0 THEN ((w.f_current_price - w.h_price) / w.h_price * 100) ELSE 0 END as change_percent
        FROM WithHistory w
        WHERE w.h_price > 0
    )
    SELECT 
        c.f_symbol, c.f_market, c.f_name, c.change_percent
    FROM CalculatedResults c
    ORDER BY c.change_percent DESC
    LIMIT limit_val;
END; $$;

-- 4. Screener Logic (V7.2 - Search Optimized)
-- =========================================================================================

DROP FUNCTION IF EXISTS public.get_stocks(text,date,text,text,text,text,text,integer,integer);

-- MAIN STOCK TABLE (Search Optimized)
CREATE OR REPLACE FUNCTION public.get_stocks(
    target_market TEXT DEFAULT NULL,
    target_date DATE DEFAULT NULL,
    search_term TEXT DEFAULT NULL,
    target_rating TEXT DEFAULT NULL,
    target_technical_rating TEXT DEFAULT NULL,
    sort_by TEXT DEFAULT 'rating_change_date',
    sort_order TEXT DEFAULT 'desc',
    limit_val INT DEFAULT 100,
    offset_val INT DEFAULT 0
)
RETURNS TABLE (
    id BIGINT, symbol TEXT, market TEXT, name TEXT,
    current_price NUMERIC, previous_price NUMERIC, 
    change NUMERIC, change_percent NUMERIC,
    technical_score NUMERIC, 
    "Technical_Rating" TEXT, "Previous_Rating" TEXT,
    rating_change_date DATE, fetched_date DATE, fetched_time TIME
) 
LANGUAGE plpgsql AS $$
DECLARE
    base_date DATE := COALESCE(target_date, CURRENT_DATE);
    lookback_days INT := CASE WHEN (search_term IS NOT NULL AND search_term != '') THEN 365 ELSE 90 END;
BEGIN
    RETURN QUERY
    WITH StockCandidates AS (
        SELECT sr.*
        FROM public.stock_ratings sr
        WHERE sr.fetched_date >= (base_date - (lookback_days || ' days')::INTERVAL)
          AND sr.fetched_date <= base_date
          AND (target_market IS NULL OR target_market = '' OR sr.market = target_market)
          AND sr.symbol NOT LIKE 'OTC:%'
    ),
    UniqueStocks AS (
        SELECT DISTINCT ON (t.symbol) t.*
        FROM StockCandidates t
        WHERE (search_term IS NULL OR search_term = '' OR t.symbol ILIKE '%' || search_term || '%' OR t.name ILIKE '%' || search_term || '%')
        ORDER BY t.symbol, t.fetched_date DESC, t.fetched_time DESC
    ),
    TopStocks AS (
        SELECT 
            u.id, u.symbol, u.market, u.name, 
            u.current_price, u.technical_score, 
            u.technical_rating, u.rating_change_date, 
            u.fetched_date, u.fetched_time,
            u.change_percent, u.price_change, u.previous_price
        FROM UniqueStocks u
        WHERE u.current_price >= 0.2
          AND u.symbol NOT LIKE 'OTC:%'
          AND u.technical_rating != 'Neutral'
          AND (target_rating IS NULL OR target_rating = '' OR u.technical_rating = target_rating)
          AND (target_technical_rating IS NULL OR target_technical_rating = ''
               OR (target_technical_rating = 'Positive' AND u.technical_rating IN ('Strong Buy', 'Buy'))
               OR (target_technical_rating = 'Negative' AND u.technical_rating IN ('Strong Sell', 'Sell')))
        ORDER BY 
            CASE WHEN search_term IS NOT NULL AND search_term != '' THEN 
                CASE WHEN u.symbol ILIKE search_term THEN 0 
                     WHEN u.symbol ILIKE search_term || '%' THEN 1 
                     ELSE 2 END
            END ASC,
            CASE WHEN sort_by = 'change' AND sort_order = 'asc' THEN u.price_change END ASC NULLS LAST,
            CASE WHEN sort_by = 'change' AND sort_order = 'desc' THEN u.price_change END DESC NULLS LAST,
            CASE WHEN sort_by = 'changePercent' AND sort_order = 'asc' THEN u.change_percent END ASC NULLS LAST,
            CASE WHEN sort_by = 'changePercent' AND sort_order = 'desc' THEN u.change_percent END DESC NULLS LAST,
            CASE WHEN sort_by = 'current_price' AND sort_order = 'asc' THEN u.current_price END ASC NULLS LAST,
            CASE WHEN sort_by = 'current_price' AND sort_order = 'desc' THEN u.current_price END DESC NULLS LAST,
            CASE WHEN sort_by = 'symbol' AND sort_order = 'asc' THEN u.symbol END ASC NULLS LAST,
            CASE WHEN sort_by = 'symbol' AND sort_order = 'desc' THEN u.symbol END DESC NULLS LAST,
            CASE WHEN sort_by = 'rating_change_date' AND sort_order = 'asc' THEN u.rating_change_date END ASC NULLS LAST,
            CASE WHEN sort_by = 'rating_change_date' AND sort_order = 'desc' THEN u.rating_change_date END DESC NULLS LAST,
            u.symbol ASC
        LIMIT limit_val OFFSET offset_val
    ),
    WithHistory AS (
        SELECT 
            t.*,
            pre.h_rating, 
            COALESCE(NULLIF(t.previous_price, 0), pre.h_price, 0) as effective_prev_price
        FROM TopStocks t
        LEFT JOIN LATERAL (
            SELECT p.technical_rating as h_rating, p.current_price as h_price
            FROM public.stock_ratings p
            WHERE p.symbol = t.symbol
              AND (p.fetched_date < t.fetched_date OR (p.fetched_date = t.fetched_date AND p.fetched_time < t.fetched_time))
              AND p.technical_rating != t.technical_rating
              AND p.technical_rating != 'Neutral'
            ORDER BY p.fetched_date DESC, p.fetched_time DESC
            LIMIT 1
        ) pre ON TRUE
    )
    SELECT 
        w.id, w.symbol, w.market, w.name, 
        w.current_price, 
        w.effective_prev_price as previous_price,
        w.price_change as change,
        w.change_percent,
        w.technical_score, w.technical_rating as "Technical_Rating",
        COALESCE(w.h_rating, 'N/A') as "Previous_Rating",
        w.rating_change_date, w.fetched_date, w.fetched_time
    FROM WithHistory w
    ORDER BY 
       CASE WHEN sort_by = 'rating_change_date' THEN w.rating_change_date END DESC,
       w.symbol ASC;
END; $$;
