    -- =========================================================================================
    -- MASTER SETUP SCRIPT: Stock Screener Database (V2 HIGH PERFORMANCE & FIXED)
    -- Combined Version: Tables + Pre-Calculated Columns + Indexes + UI Functions
    -- =========================================================================================

    -- 1. Core Database Schema
    -- =========================================================================================

    -- Main table for stock ratings and prices
    CREATE TABLE IF NOT EXISTS public.stock_ratings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        symbol TEXT NOT NULL,
        market TEXT,
        name TEXT,
        current_price NUMERIC,
        open NUMERIC,
        premarket_close NUMERIC,
        premarket_open NUMERIC,
        postmarket_close NUMERIC,
        postmarket_open NUMERIC,
        sector TEXT,
        industry TEXT,
        technical_score NUMERIC,
        technical_rating TEXT,
        fetched_date DATE DEFAULT CURRENT_DATE,
        fetched_time TIME DEFAULT CURRENT_TIME,
        session_type TEXT DEFAULT 'post_market',
        rating_change_date DATE,
        previous_price NUMERIC DEFAULT 0,
        price_change NUMERIC DEFAULT 0,
        change_percent NUMERIC DEFAULT 0,
        -- NEW COLUMNS FOR HIGH PERFORMANCE
        daily_change_percent NUMERIC,
        daily_change_amount NUMERIC,
        prev_close_price NUMERIC
    );

    -- Ensure all columns exist (Migration for existing tables)
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS open NUMERIC;
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS premarket_close NUMERIC;
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS premarket_open NUMERIC;
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS postmarket_close NUMERIC;
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS postmarket_open NUMERIC;
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS sector TEXT;
    ALTER TABLE public.stock_ratings ADD COLUMN IF NOT EXISTS industry TEXT;

    -- Table for tracking trading performance/returns
    CREATE TABLE IF NOT EXISTS public.signal_returns (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        symbol TEXT NOT NULL,
        market TEXT,
        signal_date DATE NOT NULL,
        from_rating TEXT NOT NULL,
        to_rating TEXT NOT NULL,
        signal_entry_price NUMERIC NOT NULL,
        price_after_1d NUMERIC,
        price_after_10d NUMERIC,
        price_after_30d NUMERIC,
        return_1d NUMERIC,
        return_10d NUMERIC,
        return_30d NUMERIC,
        return_1d_calculated_at TIMESTAMPTZ,
        return_10d_calculated_at TIMESTAMPTZ,
        return_30d_calculated_at TIMESTAMPTZ,
        status TEXT DEFAULT 'active',
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Ensure schema compatibility for signal_returns
    DO $$ 
    BEGIN 
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signal_returns' AND column_name='entry_date') THEN
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signal_returns' AND column_name='date') THEN
                ALTER TABLE public.signal_returns RENAME COLUMN date TO entry_date;
            ELSE
                ALTER TABLE public.signal_returns ADD COLUMN entry_date DATE;
            END IF;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signal_returns' AND column_name='entry_price') THEN
            IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='signal_returns' AND column_name='price') THEN
                ALTER TABLE public.signal_returns RENAME COLUMN price TO entry_price;
            ELSE
                ALTER TABLE public.signal_returns ADD COLUMN entry_price NUMERIC;
            END IF;
        END IF;
    END $$;

    -- 2. Performance Optimization Indexes (COMPLETE SET)
    -- =========================================================================================

    -- Enable pg_trgm extension for fast fuzzy search
    CREATE EXTENSION IF NOT EXISTS pg_trgm;

    -- Optimize LATERAL Join Performance
    CREATE INDEX IF NOT EXISTS idx_stock_ratings_lateral_opt 
    ON public.stock_ratings (symbol, fetched_date DESC, fetched_time DESC, technical_rating)
    INCLUDE (current_price);

    -- Optimize Main Screener Filtering
    CREATE INDEX IF NOT EXISTS idx_stock_ratings_screener_cover 
    ON public.stock_ratings (fetched_date DESC, market, technical_rating)
    INCLUDE (symbol, name, current_price, technical_score, rating_change_date)
    WHERE symbol NOT LIKE 'OTC:%';

    -- Speed up deduplication sorting (Recursive CTE Skip Scan)
    DROP INDEX IF EXISTS idx_stock_ratings_latest_lookup;
    CREATE INDEX idx_stock_ratings_latest_lookup 
    ON public.stock_ratings (symbol, fetched_date DESC, fetched_time DESC)
    INCLUDE (id, current_price, daily_change_percent, technical_rating, market, name, sector, industry, open);

    -- Optimize Search Performance (Text Search - Trigram GIN)
    CREATE INDEX IF NOT EXISTS idx_stock_ratings_symbol_trgm_gin 
    ON public.stock_ratings USING gin (symbol gin_trgm_ops);

    CREATE INDEX IF NOT EXISTS idx_stock_ratings_name_trgm_gin 
    ON public.stock_ratings USING gin (name gin_trgm_ops);

    -- NEW INDEXES FOR HIGH PERFORMANCE SORTING (Added per request)
    CREATE INDEX IF NOT EXISTS idx_stock_ratings_daily_change_percent 
        ON public.stock_ratings(daily_change_percent DESC NULLS LAST);

    CREATE INDEX IF NOT EXISTS idx_stock_ratings_daily_change_amount 
        ON public.stock_ratings(daily_change_amount DESC NULLS LAST);

    CREATE INDEX IF NOT EXISTS idx_stock_ratings_prev_close 
        ON public.stock_ratings(prev_close_price);

    -- Optimize Default Sort (rating_change_date) - NEW
    CREATE INDEX IF NOT EXISTS idx_stock_ratings_rating_date_sort
        ON public.stock_ratings(rating_change_date DESC NULLS LAST);

    -- Optimize Default Filter (fetched_date) - NEW
    CREATE INDEX IF NOT EXISTS idx_stock_ratings_fetched_date_sort
        ON public.stock_ratings(fetched_date DESC NULLS LAST);

    -- Index for signal_returns lookups
    CREATE INDEX IF NOT EXISTS idx_signal_returns_symbol_date 
    ON public.signal_returns (symbol, entry_date);


    -- 3. Triggers for Auto-Calculation
    -- =========================================================================================

    -- Trigger 1: Auto Calculate Daily Metrics (Change %, Amount)
    CREATE OR REPLACE FUNCTION public.calculate_daily_metrics()
    RETURNS TRIGGER AS $$
    DECLARE
        prev_record RECORD;
    BEGIN
        SELECT current_price, fetched_date INTO prev_record
        FROM public.stock_ratings
        WHERE symbol = NEW.symbol
        AND (fetched_date < NEW.fetched_date OR (fetched_date = NEW.fetched_date AND fetched_time < NEW.fetched_time))
        AND session_type = 'post_market'
        ORDER BY fetched_date DESC, fetched_time DESC
        LIMIT 1;
    
        IF FOUND THEN
            NEW.prev_close_price := prev_record.current_price;
            IF prev_record.current_price > 0 THEN
                NEW.daily_change_percent := ((NEW.current_price - prev_record.current_price) / prev_record.current_price * 100);
                NEW.daily_change_amount := (NEW.current_price - prev_record.current_price);
            ELSE
                NEW.daily_change_percent := 0;
                NEW.daily_change_amount := 0;
            END IF;
        ELSE
            NEW.prev_close_price := NULL;
            NEW.daily_change_percent := 0;
            NEW.daily_change_amount := 0;
        END IF;
    
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    DROP TRIGGER IF EXISTS trigger_calculate_daily_metrics ON public.stock_ratings;
    CREATE TRIGGER trigger_calculate_daily_metrics
        BEFORE INSERT ON public.stock_ratings
        FOR EACH ROW
        EXECUTE FUNCTION public.calculate_daily_metrics();

    -- Trigger 2: Auto Calculate Rating Change Date (Streak)
    CREATE OR REPLACE FUNCTION public.auto_calculate_rating_date()
    RETURNS TRIGGER AS $$
    DECLARE
        last_rating TEXT;
        last_change_date DATE;
    BEGIN
        SELECT technical_rating, rating_change_date
        INTO last_rating, last_change_date
        FROM public.stock_ratings
        WHERE symbol = NEW.symbol
        ORDER BY fetched_date DESC, fetched_time DESC
        LIMIT 1;

        IF last_rating IS NULL THEN
            NEW.rating_change_date := NEW.fetched_date;
        ELSIF last_rating = NEW.technical_rating THEN
            NEW.rating_change_date := last_change_date;
        ELSE
            NEW.rating_change_date := NEW.fetched_date;
        END IF;

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    DROP TRIGGER IF EXISTS trigger_calc_rating_date ON public.stock_ratings;
    CREATE TRIGGER trigger_calc_rating_date
    BEFORE INSERT ON public.stock_ratings
    FOR EACH ROW
    EXECUTE FUNCTION public.auto_calculate_rating_date();


    -- 4. UI & Dashboard Functions (Optimized & FIXED TYPES)
    -- =========================================================================================

    -- Clean up old functions (Required because parameter names were changed to p_ prefix)
    DROP FUNCTION IF EXISTS public.get_dashboard_stats(text,date);
    DROP FUNCTION IF EXISTS public.get_stocks_count_filtered(text,date,text,text,text);
    DROP FUNCTION IF EXISTS public.get_stocks_count_filtered(text,date,text,text,text,integer);
    DROP FUNCTION IF EXISTS public.get_top_gainers(text,date,integer);
    DROP FUNCTION IF EXISTS public.get_stocks(text,date,text,text,text);
    DROP FUNCTION IF EXISTS public.get_stocks(text,date,text,text,text,text,text,integer,integer);
    DROP FUNCTION IF EXISTS public.get_stocks(text,date,text,text,text,text,text,integer,integer,integer);

    -- DASHBOARD STATS
    CREATE OR REPLACE FUNCTION public.get_dashboard_stats(p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL) 
    RETURNS JSON LANGUAGE plpgsql AS $$
    DECLARE 
        result JSON;
        v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
    BEGIN
        WITH RECURSIVE LatestIds AS (
            (SELECT id, symbol FROM public.stock_ratings 
             WHERE fetched_date >= (v_base_date - INTERVAL '60 days') AND fetched_date <= v_base_date
             ORDER BY symbol ASC, fetched_date DESC, fetched_time DESC LIMIT 1)
            UNION ALL
            SELECT sr.id, sr.symbol FROM LatestIds t,
            LATERAL (
                SELECT s.id, s.symbol FROM public.stock_ratings s 
                WHERE s.symbol > t.symbol AND s.fetched_date >= (v_base_date - INTERVAL '60 days') AND s.fetched_date <= v_base_date
                ORDER BY s.symbol ASC, s.fetched_date DESC, s.fetched_time DESC LIMIT 1
            ) sr
        ),
        LatestPerSymbol AS (
            SELECT sr.technical_rating, sr.fetched_date, sr.current_price
            FROM LatestIds l JOIN public.stock_ratings sr ON sr.id = l.id
            WHERE (p_market IS NULL OR p_market = '' OR sr.market = p_market)
            AND sr.symbol NOT LIKE 'OTC:%'
        )
        SELECT json_build_object(
            'total_positive', COUNT(*) FILTER (WHERE l.technical_rating IN ('Strong Buy', 'Buy')),
            'total_negative', COUNT(*) FILTER (WHERE l.technical_rating IN ('Strong Sell', 'Sell')),
            'strong_buy', COUNT(*) FILTER (WHERE l.technical_rating = 'Strong Buy'),
            'buy', COUNT(*) FILTER (WHERE l.technical_rating = 'Buy'),
            'strong_sell', COUNT(*) FILTER (WHERE l.technical_rating = 'Strong Sell'),
            'sell', COUNT(*) FILTER (WHERE l.technical_rating = 'Sell'),
            'neutral', COUNT(*) FILTER (WHERE l.technical_rating = 'Neutral'),
            'date', MAX(l.fetched_date) 
        ) INTO result
        FROM LatestPerSymbol l
        WHERE l.current_price >= 0.2 AND l.technical_rating != 'Neutral';
        RETURN result;
    END; $$;

    -- TOTAL COUNT FILTERED
    CREATE OR REPLACE FUNCTION public.get_stocks_count_filtered(
        p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL, p_search TEXT DEFAULT NULL, 
        p_rating TEXT DEFAULT NULL, p_tech_rating TEXT DEFAULT NULL, p_lookback INT DEFAULT 60
    )
    RETURNS TABLE (res_total BIGINT) LANGUAGE plpgsql AS $$
    DECLARE v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
    BEGIN
        RETURN QUERY 
        WITH RECURSIVE LatestIds AS (
            (SELECT id, symbol FROM public.stock_ratings 
             WHERE fetched_date >= (v_base_date - (COALESCE(p_lookback, 60) || ' days')::INTERVAL) AND fetched_date <= v_base_date
             ORDER BY symbol ASC, fetched_date DESC, fetched_time DESC LIMIT 1)
            UNION ALL
            SELECT sr.id, sr.symbol FROM LatestIds t,
            LATERAL (
                SELECT s.id, s.symbol FROM public.stock_ratings s 
                WHERE s.symbol > t.symbol AND s.fetched_date >= (v_base_date - (COALESCE(p_lookback, 60) || ' days')::INTERVAL) AND s.fetched_date <= v_base_date
                ORDER BY s.symbol ASC, s.fetched_date DESC, s.fetched_time DESC LIMIT 1
            ) sr
        ),
        UniqueStocks AS (
            SELECT sr.technical_rating, sr.current_price, sr.market, sr.symbol, sr.name
            FROM LatestIds l JOIN public.stock_ratings sr ON sr.id = l.id
            WHERE (p_market IS NULL OR p_market = '' OR sr.market = p_market)
            AND sr.symbol NOT LIKE 'OTC:%'
            AND (p_search IS NULL OR p_search = '' OR sr.symbol ILIKE '%' || p_search || '%' OR sr.name ILIKE '%' || p_search || '%')
        )
        SELECT COUNT(*) FROM UniqueStocks u
        WHERE u.current_price >= 0.2 AND u.technical_rating != 'Neutral'
        AND (p_rating IS NULL OR p_rating = '' OR u.technical_rating = p_rating)
        AND (p_tech_rating IS NULL OR p_tech_rating = ''
            OR (p_tech_rating = 'Positive' AND u.technical_rating IN ('Strong Buy', 'Buy'))
            OR (p_tech_rating = 'Negative' AND u.technical_rating IN ('Strong Sell', 'Sell')));
    END; $$;

    -- TOP GAINER (Ultra Fast - Uses Pre-Calculated Column)
    CREATE OR REPLACE FUNCTION public.get_top_gainers(
        p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL, p_limit INTEGER DEFAULT 3
    )
    RETURNS TABLE (
        res_symbol TEXT,
        res_market TEXT,
        res_name TEXT,
        res_price NUMERIC,
        res_change_pct NUMERIC,
        res_date DATE
    ) LANGUAGE plpgsql AS $$
    DECLARE v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
    BEGIN
        RETURN QUERY
        WITH LatestStocks AS (
            SELECT DISTINCT ON (sr.symbol) sr.symbol, sr.market, sr.name, sr.current_price, sr.daily_change_percent, sr.fetched_date, sr.fetched_time
            FROM public.stock_ratings sr
            WHERE sr.fetched_date >= (v_base_date - INTERVAL '5 days') AND sr.fetched_date <= v_base_date
              AND sr.technical_rating != 'Neutral' 
            ORDER BY sr.symbol, sr.fetched_date DESC, sr.fetched_time DESC
        )
        SELECT ls.symbol, ls.market, ls.name, ls.current_price, COALESCE(ls.daily_change_percent, 0), ls.fetched_date
        FROM LatestStocks ls
        WHERE (p_market IS NULL OR p_market = '' OR ls.market = p_market)
           AND ls.symbol NOT LIKE 'OTC:%' AND ls.current_price >= 0.2
           AND ls.daily_change_percent IS NOT NULL AND ls.daily_change_percent > 0
        ORDER BY ls.daily_change_percent DESC LIMIT p_limit;
    END; $$;

    -- MAIN STOCK TABLE (FIXED TYPES: BIGINT, NUMERIC, DATE)
    CREATE OR REPLACE FUNCTION public.get_stocks(
        p_market TEXT DEFAULT NULL, p_date DATE DEFAULT NULL, p_search TEXT DEFAULT NULL,
        p_rating TEXT DEFAULT NULL, p_tech_rating TEXT DEFAULT NULL,
        p_sort_by TEXT DEFAULT 'rating_change_date', p_sort_order TEXT DEFAULT 'desc',
        p_limit INTEGER DEFAULT 50, p_offset INTEGER DEFAULT 0, p_lookback INTEGER DEFAULT 60
    )
    RETURNS TABLE (
        res_id BIGINT,
        res_symbol TEXT,
        res_market TEXT,
        res_name TEXT,
        res_current_price NUMERIC,
        res_open NUMERIC,
        res_premarket_close NUMERIC,
        res_premarket_open NUMERIC,
        res_postmarket_close NUMERIC,
        res_postmarket_open NUMERIC,
        res_sector TEXT,
        res_industry TEXT,
        res_previous_price NUMERIC,
        res_change NUMERIC,
        res_change_pct NUMERIC,
        res_technical_score NUMERIC,
        res_technical_rating TEXT,
        res_previous_rating TEXT,
        res_rating_change_date DATE,
        res_fetched_date DATE,
        res_fetched_time TIME
    ) AS $$
    DECLARE v_base_date DATE := COALESCE(p_date, CURRENT_DATE);
    BEGIN
        RETURN QUERY
        WITH RECURSIVE LatestIds AS (
            (SELECT id, symbol FROM public.stock_ratings 
             WHERE fetched_date >= (v_base_date - (COALESCE(p_lookback, 60) || ' days')::INTERVAL) AND fetched_date <= v_base_date
             ORDER BY symbol ASC, fetched_date DESC, fetched_time DESC LIMIT 1)
            UNION ALL
            SELECT sr.id, sr.symbol FROM LatestIds t,
            LATERAL (
                SELECT s.id, s.symbol FROM public.stock_ratings s 
                WHERE s.symbol > t.symbol AND s.fetched_date >= (v_base_date - (COALESCE(p_lookback, 60) || ' days')::INTERVAL) AND s.fetched_date <= v_base_date
                ORDER BY s.symbol ASC, s.fetched_date DESC, s.fetched_time DESC LIMIT 1
            ) sr
        ),
        LatestPerSymbol AS (
            SELECT sr.id, sr.symbol, sr.daily_change_percent, sr.daily_change_amount, 
                   sr.technical_rating, sr.current_price, sr.rating_change_date, sr.market, sr.name,
                    sr.fetched_date, sr.fetched_time, sr.technical_score, sr.prev_close_price,
                    sr.open, sr.premarket_close, sr.premarket_open, sr.postmarket_close, sr.postmarket_open,
                    sr.sector, sr.industry,
                    -- Extract exchange and symbol parts for proper sorting
                   -- exchange: everything before ':', fallback to symbol if no ':'
                   SPLIT_PART(sr.symbol, ':', 1) as exchange,
                   -- symbol_only: everything after ':', fallback to full symbol if no ':'
                   COALESCE(NULLIF(SPLIT_PART(sr.symbol, ':', 2), ''), sr.symbol) as symbol_only
            FROM LatestIds l JOIN public.stock_ratings sr ON sr.id = l.id
            WHERE (p_market IS NULL OR p_market = '' OR sr.market = p_market)
            AND sr.symbol NOT LIKE 'OTC:%'
            AND (p_search IS NULL OR p_search = '' OR sr.symbol ILIKE '%' || p_search || '%' OR sr.name ILIKE '%' || p_search || '%')
        ),
        CandidateIds AS (
            SELECT l.*
            FROM LatestPerSymbol l
            WHERE l.current_price >= 0.2 AND l.technical_rating != 'Neutral'
              AND (p_rating IS NULL OR p_rating = '' OR l.technical_rating = p_rating)
              AND (p_tech_rating IS NULL OR p_tech_rating = ''
                   OR (p_tech_rating = 'Positive' AND l.technical_rating IN ('Strong Buy', 'Buy'))
                   OR (p_tech_rating = 'Negative' AND l.technical_rating IN ('Strong Sell', 'Sell')))
        ),
        SortedIds AS (
            SELECT * FROM CandidateIds
            ORDER BY
                -- Handle search ranking
                CASE WHEN p_search IS NOT NULL AND p_search != '' THEN 
                    CASE WHEN symbol ILIKE p_search THEN 0 
                        WHEN symbol ILIKE p_search || '%' THEN 1 
                        ELSE 2 END
                END ASC,
                -- Core Sorting
                CASE WHEN p_sort_by = 'top_gainers' THEN daily_change_percent END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'changePercent' AND p_sort_order = 'asc' THEN daily_change_percent END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'changePercent' AND p_sort_order = 'desc' THEN daily_change_percent END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'change' AND p_sort_order = 'asc' THEN daily_change_amount END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'change' AND p_sort_order = 'desc' THEN daily_change_amount END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'asc' THEN current_price END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'desc' THEN current_price END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'symbol' AND p_sort_order = 'asc' THEN symbol_only END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'symbol' AND p_sort_order = 'desc' THEN symbol_only END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'exchange' AND p_sort_order = 'asc' THEN exchange END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'exchange' AND p_sort_order = 'desc' THEN exchange END DESC NULLS LAST,
                CASE WHEN p_sort_by = 'rating_change_date' AND p_sort_order = 'asc' THEN rating_change_date END ASC NULLS LAST,
                CASE WHEN p_sort_by = 'rating_change_date' AND p_sort_order = 'desc' THEN rating_change_date END DESC NULLS LAST,
                symbol ASC
            LIMIT p_limit OFFSET p_offset
        ),
        WithFullData AS (
            SELECT s.*, 
                pre.h_rating,
                pre.h_price
            FROM SortedIds s
            LEFT JOIN LATERAL (
                SELECT p.technical_rating as h_rating, p.current_price as h_price
                FROM public.stock_ratings p 
                WHERE p.symbol = s.symbol 
                AND (p.fetched_date < s.fetched_date OR (p.fetched_date = s.fetched_date AND p.fetched_time < s.fetched_time))
                AND p.technical_rating != s.technical_rating AND p.technical_rating != 'Neutral'
                ORDER BY p.fetched_date DESC, p.fetched_time DESC LIMIT 1) pre ON TRUE
        )
        SELECT 
            w.id, w.symbol, w.market, w.name, w.current_price, 
            w.open, w.premarket_close, w.premarket_open, w.postmarket_close, w.postmarket_open,
            w.sector, w.industry,
            COALESCE(NULLIF(w.prev_close_price, 0), w.h_price, 0), -- Use prev_close_price instead of previous_price
            COALESCE(w.daily_change_amount, 0), 
            COALESCE(w.daily_change_percent, 0),
            w.technical_score, w.technical_rating, 
            COALESCE(w.h_rating, 'N/A'),
            w.rating_change_date, w.fetched_date, w.fetched_time
        FROM WithFullData w
        ORDER BY -- Maintain final presentation order
            CASE WHEN p_search IS NOT NULL AND p_search != '' THEN 
                CASE WHEN w.symbol ILIKE p_search THEN 0 
                    WHEN w.symbol ILIKE p_search || '%' THEN 1 
                    ELSE 2 END
            END ASC,
            CASE WHEN p_sort_by = 'top_gainers' THEN w.daily_change_percent END DESC NULLS LAST,
            CASE WHEN p_sort_by = 'changePercent' AND p_sort_order = 'asc' THEN w.daily_change_percent END ASC NULLS LAST,
            CASE WHEN p_sort_by = 'changePercent' AND p_sort_order = 'desc' THEN w.daily_change_percent END DESC NULLS LAST,
            CASE WHEN p_sort_by = 'change' AND p_sort_order = 'asc' THEN w.daily_change_amount END ASC NULLS LAST,
            CASE WHEN p_sort_by = 'change' AND p_sort_order = 'desc' THEN w.daily_change_amount END DESC NULLS LAST,
            CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'asc' THEN w.current_price END ASC NULLS LAST,
            CASE WHEN p_sort_by = 'current_price' AND p_sort_order = 'desc' THEN w.current_price END DESC NULLS LAST,
            CASE WHEN p_sort_by = 'symbol' AND p_sort_order = 'asc' THEN w.symbol_only END ASC NULLS LAST,
            CASE WHEN p_sort_by = 'symbol' AND p_sort_order = 'desc' THEN w.symbol_only END DESC NULLS LAST,
            CASE WHEN p_sort_by = 'exchange' AND p_sort_order = 'asc' THEN w.exchange END ASC NULLS LAST,
            CASE WHEN p_sort_by = 'exchange' AND p_sort_order = 'desc' THEN w.exchange END DESC NULLS LAST,
            CASE WHEN p_sort_by = 'rating_change_date' AND p_sort_order = 'asc' THEN w.rating_change_date END ASC NULLS LAST,
            CASE WHEN p_sort_by = 'rating_change_date' AND p_sort_order = 'desc' THEN w.rating_change_date END DESC NULLS LAST,
            w.symbol ASC;
    END; $$ LANGUAGE plpgsql;

    -- 5. Backfill Helper (For Setup Script)
    -- =========================================================================================
    CREATE OR REPLACE FUNCTION public.backfill_next_batch(batch_size INTEGER)
    RETURNS INTEGER AS $$
    DECLARE rows_updated INTEGER;
    BEGIN
        WITH TargetRows AS (
            SELECT id, symbol, fetched_date, fetched_time FROM public.stock_ratings WHERE daily_change_percent IS NULL ORDER BY fetched_date DESC, fetched_time DESC LIMIT batch_size
        )
        UPDATE public.stock_ratings sr
        SET prev_close_price = prev.current_price, daily_change_percent = CASE WHEN prev.current_price > 0 THEN ((sr.current_price - prev.current_price) / prev.current_price * 100) ELSE 0 END, daily_change_amount = (sr.current_price - prev.current_price)
        FROM TargetRows t
        LEFT JOIN LATERAL (SELECT current_price FROM public.stock_ratings p WHERE p.symbol = t.symbol AND (p.fetched_date < t.fetched_date OR (p.fetched_date = t.fetched_date AND p.fetched_time < t.fetched_time)) AND p.session_type = 'post_market' ORDER BY p.fetched_date DESC, p.fetched_time DESC LIMIT 1) prev ON TRUE
        WHERE sr.id = t.id;
        GET DIAGNOSTICS rows_updated = ROW_COUNT;
        RETURN rows_updated;
    END; $$ LANGUAGE plpgsql;
